AdobeDocs/commerce-pwa-studio

src/pages/integrations/pagebuilder/components/HTML-Code/index.md
Fix a filename casing issue causing a crash on gh build.
Introduced in #7 
Fixes a bug
N/A
=> [bugfix] Fix filename casing issue

src/pages/api/venia/components/general/Link/index.md, src/pages/api/venia/components/general/Shimmer/index.md
Updates from Shimmer review [PR-3548](https://github.com/magento/pwa-studio/pull/3548) 
[PR-3548](https://github.com/magento/pwa-studio/pull/3548)
=> Updates from shimmer docs review

src/pages/guides/upgrading-versions/index.md
Added title to Upgrade versions page.
=> Forgot to add an H1 heading

src/data/navigation/sections/metapackages.js
Updated side-navigation to add Venia sample data installation topic.
=> Updated side-navigation for sample data topic

src/pages/metapackages/index.md
This PR adds the missing link definition to the PWA Open Source metapackage.
Missing link.
Local build and clicking link from page.
=> Added missing link to Open Source metapackage

src/pages/metapackages/open-source/index.md
Fixed the git clone path to fix the "Repository not found" issue.
It was throwing the error
`ERROR: Repository not found.`
By running the command with the correct clone path
`git clone git@github.com:magento/magento2-pwa.git ext/magento/magento2-pwa`
=> Fix the git clone path

src/pages/guides/project/faq/index.md
This PR removes a link to an outdated resource per team discussion.
No need to have stale links.
=> Removing outdated link

src/pages/integrations/product-recommendations/index.md
Fixing some typos on the "fetch data only" section
When we copy past the code we get some errors.
=> Fixing some typos on the "fetch data only" section

src/pages/guides/project/faq/index.md
=> FAQ by pass styleloader for external styling

src/data/navigation/sections/integrations.js, src/data/navigation/sections/tutorials.js, src/pages/integrations/adobe-commerce/index.md, src/pages/tutorials/basic-modifications/index.md, src/pages/tutorials/setup-storefront/issues/index.md, src/pages/tutorials/targets/modify-talon-results/index.md
This PR fixes broken links in the docs.
Fixes #94
Fixes #98 
Fixes #99
=> Fixed links and added landing pages

src/pages/api/buildpack/cli/create-project/index.md, src/pages/guides/packages/venia/sample-data/index.md
This PR removes some old devdocs notation that is not used in this repo.
=> Removed old devdocs code

src/pages/guides/packages/upward/multi-site.md
This PR adds a topic for multi-site setup for PWA/UPWARD
https://jira.corp.magento.com/browse/PWA-2562
=> Add multi-site topic

.github/PULL_REQUEST_TEMPLATE.md
This PR makes the PR template more doc specific and removes codebase style content.
=> Updating template to be more doc specific

src/data/navigation/sections/guides.js, src/pages/integrations/adobe-commerce/features/index.js
This PR updates the Commerce features supported by PWA Studio: https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/features/
https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/features/
https://developer-stage.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/features/
NA
=> Updated commerce coverage table, added missing TOC entry

src/pages/tutorials/production-deployment/adobe-commerce/index.md
This PR adds a missing step to the install tutorial.
https://developer.adobe.com/commerce/pwa-studio/tutorials/production-deployment/adobe-commerce/
=> Added missing step

src/pages/guides/general-concepts/client-side-caching/index.md, src/pages/tutorials/basic-modifications/modify-footer/index.md
This PR fixes 2 community issues.
https://developer.adobe.com/commerce/pwa-studio/guides/general-concepts/client-side-caching/#cache-first
https://developer.adobe.com/commerce/pwa-studio/tutorials/basic-modifications/modify-footer/#import-new-adapter-component
Fixes https://github.com/magento/pwa-studio/issues/3358 - PWA-2874 
Fixes https://github.com/magento/pwa-studio/issues/3366 - PWA-2873
=> Fixing a couple community issues

src/data/navigation/sections/integrations.js
This PR removed old TOC entries that are now in other places.
https://developer.adobe.com/commerce/pwa-studio/integrations/
=> Removed old TOC entries

src/pages/integrations/adobe-commerce/theme-vs-storefront/index.md, src/pages/integrations/pagebuilder/custom-components/index.md, src/pages/tutorials/extensions/taglist/index.md
Rename magento-devdocs to commerce-docs.
=> Rename magento-devdocs to commerce-docs in links

src/pages/integrations/adobe-commerce/aep/index.md
This pull request (PR) updates the PWA-AEP integration topic to reference the new feature name: Data Connection.
- https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/aep/
=> Update PWA-AEP integration

src/data/navigation/sections/tutorials.js
This pull request (PR) fixes #156 
- https://developer.adobe.com/commerce/pwa-studio/tutorials/basic-modifications/modify-footer/
- https://developer.adobe.com/commerce/pwa-studio/tutorials/extensions/taglist/
=> GH-156: Fix 404 on next page click

.github/workflows/index.yml, .github/workflows/publish.yml
This pull request (PR) enables indexing on each deployment and removes cron from the indexing workflow.
Internal request: COMDOX-990
=> Enable indexing on each deployment and remove cron for indexing

.github/workflows/publish.yml
This pull request (PR) adds a missing secret to fix the enablement of indexing during deployment.
=> Fix indexing
